// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmyynhneyeuerjskzoej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBteXluaG5leWV1ZXJqc2t6b2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzEyMDQsImV4cCI6MjA3MDI0NzIwNH0.3O-lvGlLy9DLlUP4zhrcVqgwuzblQiDWJXCf3Zb3Wo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});